version: "3.8"

services:
  mariadb:
    container_name: dev-mariadb
    command: --max-allowed-packet=64MB
    restart: always
    image: mariadb
    ports:
      - '33060:3306'
    networks:
      - dev
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mariadb

  redis:
    container_name: dev-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '63790:6379'
    networks:
      - dev
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - data:/data

  postgres:
    container_name: dev-postgres
    image: postgres:latest
    restart: always
    ports:
      - '54320:5432'
    networks:
      - dev
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev

  web:
    container_name: dev-php7-web
    build:
      context: .
      dockerfile: PHP7.Dockerfile
    ports:
      - 800:80
      - 4430:443
      - 220:22
    volumes:
      - ./:/var/www
    networks:
      - dev
    links:
      - postgres
      - mariadb
      - redis
    depends_on:
      - postgres
      - mariadb
      - redis

volumes:
  data:
    driver: local

networks:
  dev:
